"""Generate the curated dissertation figure suite from experiment outputs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib
import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import precision_recall_curve, roc_curve

matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch


_OOD_TYPE_ORDER = ["modality_shift", "sensory_artifact", "semantic_outlier"]
_SUBTYPE_ORDER = [
    "colour_fundus",
    "oct_screenshot",
    "text_watermark",
    "rectangle_annotation",
    "arrow_annotation",
    "composite_layout",
    "blur_artifact",
    "border_crop",
    "gaussian_noise",
    "jpeg_compression",
    "cifar10_natural",
]
_LAYER_ORDER = {"layer1": 1, "layer2": 2, "layer3": 3, "layer4": 4, "layer2+layer3": 5}
_PALETTE = {
    "blue": "#2F6F9F",
    "green": "#3B7F5C",
    "red": "#B85C5C",
    "gold": "#B38B2E",
    "gray": "#5B6470",
    "light_blue": "#E7F0F7",
    "light_green": "#E8F3ED",
    "light_red": "#F6E7E7",
    "light_gold": "#F8F1DF",
}


@dataclass(frozen=True)
class DissertationSuiteOutputs:
    """Paths generated by the dissertation figure suite."""

    files: dict[str, Path]


def generate_dissertation_figure_suite(
    reports_dir: str | Path,
    out_dir: str | Path = "reports/dissertation_figures",
    *,
    dpi: int = 300,
) -> DissertationSuiteOutputs:
    """Generate dissertation-ready figures, captions, and a figure index.

    ``reports_dir`` should be a grid output directory containing ``metrics_summary.csv``,
    per-category tables, and per-run ``scores.csv`` files. The function reads aggregate
    outputs only; it does not load patient identifiers or raw private metadata.
    """
    if dpi <= 0:
        raise ValueError("dpi must be positive")
    reports_dir = Path(reports_dir)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    summary = _read_required_csv(reports_dir / "metrics_summary.csv")
    per_type = _read_optional_csv(reports_dir / "per_ood_type_metrics.csv")
    per_subtype = _read_optional_csv(reports_dir / "per_ood_subtype_metrics.csv")
    summary = _prepare_summary(summary)
    scores = _load_scores_by_experiment(reports_dir, summary)
    best_experiment = _best_patchcore_experiment(summary)

    files: dict[str, Path] = {}
    files["roc_overall"] = _plot_roc_comparison(
        summary,
        scores,
        out_dir / "figure_roc_overall_model_comparison.png",
        dpi=dpi,
    )
    files["pr_overall"] = _plot_pr_comparison(
        summary,
        scores,
        out_dir / "figure_pr_overall_model_comparison.png",
        dpi=dpi,
    )
    files["metric_bars"] = _plot_metric_bars(
        summary,
        out_dir / "figure_metric_bars_main_models.png",
        dpi=dpi,
    )
    files["layer_ablation"] = _plot_layer_ablation(
        summary,
        out_dir / "figure_layer_ablation_patchcore.png",
        dpi=dpi,
    )
    files["per_ood_type"] = _plot_per_ood_type(
        summary,
        per_type,
        out_dir / "figure_per_ood_type_comparison.png",
        dpi=dpi,
    )
    files["per_ood_subtype"] = _plot_per_ood_subtype(
        summary,
        per_subtype,
        best_experiment,
        out_dir / "figure_per_ood_subtype_comparison.png",
        dpi=dpi,
    )
    files["score_distribution"] = _plot_score_distribution(
        scores,
        best_experiment,
        out_dir / "figure_score_distribution_with_threshold.png",
        dpi=dpi,
    )
    files["score_distribution_id_vs_ood"] = _plot_score_distribution(
        scores,
        best_experiment,
        out_dir / "figure_score_distribution_id_vs_ood.png",
        dpi=dpi,
    )
    files["threshold_policy"] = _plot_threshold_policy(
        scores,
        best_experiment,
        summary,
        out_dir / "figure_threshold_policy.png",
        dpi=dpi,
    )
    files["heatmaps_sensory"] = _plot_heatmap_examples(
        reports_dir,
        scores,
        best_experiment,
        "sensory_artifact",
        out_dir / "figure_heatmaps_sensory_artifact_examples.png",
        dpi=dpi,
    )
    files["heatmaps_modality"] = _plot_heatmap_examples(
        reports_dir,
        scores,
        best_experiment,
        "modality_shift",
        out_dir / "figure_heatmaps_modality_examples.png",
        dpi=dpi,
    )
    files["dataset_taxonomy"] = _plot_dataset_taxonomy(
        out_dir / "figure_dataset_taxonomy.png",
        dpi=dpi,
    )
    files["system_pipeline"] = _plot_system_pipeline(
        out_dir / "figure_system_pipeline_overview.png",
        dpi=dpi,
    )
    files["patchcore_method"] = _plot_patchcore_method(
        out_dir / "figure_patchcore_method.png",
        dpi=dpi,
    )
    files["experiment_workflow"] = _plot_experiment_workflow(
        out_dir / "figure_experiment_workflow.png",
        dpi=dpi,
    )
    files["caption_suggestions"] = _write_caption_suggestions(
        out_dir / "caption_suggestions.md",
        files,
        summary,
    )
    files["figure_index"] = _write_figure_index(out_dir / "figure_index.md", files)
    return DissertationSuiteOutputs(files=files)


def _read_required_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required CSV does not exist: {path}")
    return pd.read_csv(path)


def _read_optional_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def _prepare_summary(summary: pd.DataFrame) -> pd.DataFrame:
    required = ["experiment", "model", "layers", "auroc", "auprc", "fpr_at_95_tpr"]
    missing = [column for column in required if column not in summary.columns]
    if missing:
        raise ValueError(f"metrics_summary.csv missing required columns: {missing}")
    table = summary.copy()
    for column in [
        "auroc",
        "auprc",
        "fpr_at_95_tpr",
        "threshold",
        "threshold_at_95_tpr",
        "id_false_rejection_rate",
    ]:
        if column in table.columns:
            table[column] = pd.to_numeric(table[column], errors="coerce")
    table["figure_label"] = [_model_label(row) for _, row in table.iterrows()]
    table["sort_key"] = [_model_sort_key(row) for _, row in table.iterrows()]
    return table.sort_values(["sort_key", "experiment"], kind="stable").reset_index(drop=True)


def _load_scores_by_experiment(reports_dir: Path, summary: pd.DataFrame) -> dict[str, pd.DataFrame]:
    scores: dict[str, pd.DataFrame] = {}
    for experiment in summary["experiment"].astype(str):
        path = reports_dir / "runs" / experiment / "evaluation" / "scores.csv"
        if not path.exists():
            continue
        table = pd.read_csv(path)
        if table.empty:
            continue
        for column in ["label", "score", "threshold"]:
            if column in table.columns:
                table[column] = pd.to_numeric(table[column], errors="coerce")
        if "ood_subtype" not in table.columns:
            table["ood_subtype"] = ""
        if "ood_type" not in table.columns:
            table["ood_type"] = np.where(table["label"].astype(int) == 0, "id", "unknown")
        scores[experiment] = table
    if not scores:
        raise FileNotFoundError(f"No per-run scores.csv files found under {reports_dir / 'runs'}")
    return scores


def _best_patchcore_experiment(summary: pd.DataFrame) -> str:
    patchcore = summary[_is_patchcore(summary)]
    if patchcore.empty:
        return str(summary.sort_values("auroc", ascending=False).iloc[0]["experiment"])
    return str(patchcore.sort_values(["auroc", "auprc"], ascending=[False, False]).iloc[0]["experiment"])


def _plot_roc_comparison(
    summary: pd.DataFrame,
    scores: dict[str, pd.DataFrame],
    path: Path,
    *,
    dpi: int,
) -> Path:
    fig, ax = plt.subplots(figsize=(7.0, 5.2))
    for _, row in summary.iterrows():
        experiment = str(row["experiment"])
        if experiment not in scores:
            continue
        labels, values = _labels_scores(scores[experiment])
        if len(np.unique(labels)) < 2:
            continue
        fpr, tpr, _ = roc_curve(labels, values, pos_label=1, drop_intermediate=False)
        label = f"{row['figure_label']} (AUROC {row['auroc']:.2f})"
        ax.plot(fpr, tpr, linewidth=2.0, label=label)
    ax.plot([0, 1], [0, 1], color="#9CA3AF", linewidth=1.0, linestyle="--")
    ax.set_xlabel("False positive rate")
    ax.set_ylabel("True positive rate")
    ax.set_title("Overall ROC comparison")
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(0.0, 1.0)
    ax.grid(alpha=0.22)
    ax.legend(frameon=False, fontsize=8)
    return _save(fig, path, dpi=dpi)


def _plot_pr_comparison(
    summary: pd.DataFrame,
    scores: dict[str, pd.DataFrame],
    path: Path,
    *,
    dpi: int,
) -> Path:
    fig, ax = plt.subplots(figsize=(7.0, 5.2))
    for _, row in summary.iterrows():
        experiment = str(row["experiment"])
        if experiment not in scores:
            continue
        labels, values = _labels_scores(scores[experiment])
        if len(np.unique(labels)) < 2:
            continue
        precision, recall, _ = precision_recall_curve(labels, values, pos_label=1)
        label = f"{row['figure_label']} (AUPRC {row['auprc']:.2f})"
        ax.plot(recall, precision, linewidth=2.0, label=label)
    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_title("Overall precision-recall comparison")
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(0.0, 1.02)
    ax.grid(alpha=0.22)
    ax.legend(frameon=False, fontsize=8)
    return _save(fig, path, dpi=dpi)


def _plot_metric_bars(summary: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    labels = summary["figure_label"].astype(str).tolist()
    x = np.arange(len(summary))
    width = 0.25
    fig, ax = plt.subplots(figsize=(max(7.0, len(summary) * 1.0), 4.8))
    ax.bar(x - width, summary["auroc"], width, label="AUROC", color=_PALETTE["blue"])
    ax.bar(x, summary["auprc"], width, label="AUPRC", color=_PALETTE["green"])
    ax.bar(
        x + width,
        summary["fpr_at_95_tpr"],
        width,
        label="FPR@95%TPR",
        color=_PALETTE["red"],
    )
    ax.set_ylabel("Metric value")
    ax.set_title("Main OOD gatekeeper metrics by model")
    ax.set_ylim(0.0, 1.05)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=28, ha="right")
    ax.grid(axis="y", alpha=0.22)
    ax.legend(frameon=False, ncols=3, fontsize=8)
    return _save(fig, path, dpi=dpi)


def _plot_layer_ablation(summary: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    patchcore = summary[_is_patchcore(summary) & summary["layers"].fillna("").astype(str).ne("")]
    patchcore = patchcore.sort_values("sort_key", kind="stable")
    fig, ax = plt.subplots(figsize=(7.0, 4.8))
    if patchcore.empty:
        _empty_axis(ax, "No PatchCore layer rows available")
    else:
        x = np.arange(len(patchcore))
        ax.plot(x, patchcore["auroc"], marker="o", label="AUROC", color=_PALETTE["blue"])
        ax.plot(x, patchcore["auprc"], marker="o", label="AUPRC", color=_PALETTE["green"])
        ax.plot(
            x,
            patchcore["fpr_at_95_tpr"],
            marker="o",
            label="FPR@95%TPR",
            color=_PALETTE["red"],
        )
        ax.set_xticks(x)
        ax.set_xticklabels(patchcore["figure_label"], rotation=24, ha="right")
        ax.set_ylim(0.0, 1.05)
        ax.set_ylabel("Metric value")
        ax.grid(axis="y", alpha=0.22)
        ax.legend(frameon=False, ncols=3, fontsize=8)
    ax.set_title("PatchCore feature-layer ablation")
    return _save(fig, path, dpi=dpi)


def _plot_per_ood_type(
    summary: pd.DataFrame,
    per_type: pd.DataFrame,
    path: Path,
    *,
    dpi: int,
) -> Path:
    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    if per_type.empty:
        _empty_axis(ax, "No per-OOD-type rows available")
        return _save(fig, path, dpi=dpi)
    table = per_type.merge(
        summary[["experiment", "figure_label", "sort_key"]],
        on="experiment",
        how="left",
    )
    table["ood_type"] = pd.Categorical(table["ood_type"], _OOD_TYPE_ORDER, ordered=True)
    pivot = table.pivot_table(
        index="figure_label",
        columns="ood_type",
        values="auroc",
        aggfunc="first",
        sort=False,
        observed=False,
    )
    _draw_heatmap_table(ax, pivot, title="AUROC by OOD category", colorbar_label="AUROC")
    return _save(fig, path, dpi=dpi)


def _plot_per_ood_subtype(
    summary: pd.DataFrame,
    per_subtype: pd.DataFrame,
    best_experiment: str,
    path: Path,
    *,
    dpi: int,
) -> Path:
    fig, ax = plt.subplots(figsize=(8.0, 5.8))
    if per_subtype.empty:
        _empty_axis(ax, "No per-OOD-subtype rows available")
        return _save(fig, path, dpi=dpi)
    rows = per_subtype[per_subtype["experiment"].astype(str) == best_experiment].copy()
    if rows.empty:
        rows = per_subtype.copy()
    rows["ood_subtype"] = pd.Categorical(rows["ood_subtype"], _SUBTYPE_ORDER, ordered=True)
    rows = rows.sort_values("ood_subtype", kind="stable")
    y = np.arange(len(rows))
    values = pd.to_numeric(rows["auroc"], errors="coerce")
    ax.barh(y, values, color=_PALETTE["blue"])
    ax.set_yticks(y)
    ax.set_yticklabels(rows["ood_subtype"].astype(str))
    ax.invert_yaxis()
    ax.set_xlim(0.0, 1.0)
    ax.set_xlabel("AUROC")
    ax.set_title("Per-OOD-subtype performance for the selected PatchCore model")
    ax.grid(axis="x", alpha=0.22)
    for index, value in enumerate(values):
        if pd.notna(value):
            ax.text(min(float(value) + 0.015, 0.98), index, f"{value:.2f}", va="center", fontsize=8)
    return _save(fig, path, dpi=dpi)


def _plot_score_distribution(
    scores: dict[str, pd.DataFrame],
    experiment: str,
    path: Path,
    *,
    dpi: int,
) -> Path:
    table = scores[experiment].copy()
    table["score_group"] = np.where(table["label"].astype(int) == 0, "ID", table["ood_type"])
    order = ["ID", *_OOD_TYPE_ORDER]
    grouped = [table.loc[table["score_group"] == group, "score"].dropna().to_numpy() for group in order]
    fig, ax = plt.subplots(figsize=(7.4, 4.8))
    ax.boxplot(grouped, labels=order, showfliers=False, patch_artist=True)
    for patch, color in zip(
        ax.artists,
        [_PALETTE["light_green"], _PALETTE["light_blue"], _PALETTE["light_gold"], _PALETTE["light_red"]],
    ):
        patch.set_facecolor(color)
    threshold = _first_threshold(table)
    if threshold is not None:
        ax.axhline(threshold, color=_PALETTE["red"], linestyle="--", linewidth=1.6)
        ax.text(0.98, threshold, "deployment threshold", transform=ax.get_yaxis_transform(), ha="right", va="bottom")
    ax.set_ylabel("Anomaly score")
    ax.set_title("Score distribution with threshold")
    ax.grid(axis="y", alpha=0.22)
    return _save(fig, path, dpi=dpi)


def _plot_threshold_policy(
    scores: dict[str, pd.DataFrame],
    experiment: str,
    summary: pd.DataFrame,
    path: Path,
    *,
    dpi: int,
) -> Path:
    table = scores[experiment]
    row = summary[summary["experiment"].astype(str) == experiment].iloc[0]
    deployment = _first_threshold(table)
    research = row.get("threshold_at_95_tpr", np.nan)
    fig, ax = plt.subplots(figsize=(7.2, 4.6))
    id_scores = table.loc[table["label"].astype(int) == 0, "score"].astype(float)
    ood_scores = table.loc[table["label"].astype(int) == 1, "score"].astype(float)
    bins = max(8, min(30, int(np.sqrt(len(table))) + 3))
    ax.hist(id_scores, bins=bins, alpha=0.65, label="ID", color=_PALETTE["green"], density=True)
    ax.hist(ood_scores, bins=bins, alpha=0.55, label="OOD", color=_PALETTE["blue"], density=True)
    if deployment is not None:
        ax.axvline(deployment, color=_PALETTE["red"], linestyle="--", label="deployment threshold")
    if pd.notna(research):
        ax.axvline(float(research), color=_PALETTE["gold"], linestyle=":", label="research threshold")
    ax.set_xlabel("Anomaly score")
    ax.set_ylabel("Density")
    ax.set_title("Threshold decision policy")
    ax.legend(frameon=False)
    ax.grid(axis="y", alpha=0.22)
    return _save(fig, path, dpi=dpi)


def _plot_heatmap_examples(
    reports_dir: Path,
    scores: dict[str, pd.DataFrame],
    experiment: str,
    ood_type: str,
    path: Path,
    *,
    dpi: int,
) -> Path:
    heatmap_manifest = _find_heatmap_manifest(reports_dir, experiment)
    fig, axes = plt.subplots(1, 3, figsize=(8.4, 3.2))
    for axis in np.ravel(axes):
        axis.axis("off")
    if heatmap_manifest is None:
        axes[0].text(0.5, 0.5, "No heatmap manifest available", ha="center", va="center")
        return _save(fig, path, dpi=dpi)

    heatmaps = pd.read_csv(heatmap_manifest)
    score_rows = scores.get(experiment, pd.DataFrame())
    if not score_rows.empty:
        heatmaps = heatmaps.merge(
            score_rows[["image_path", "ood_type", "ood_subtype"]],
            on="image_path",
            how="left",
            suffixes=("", "_score"),
        )
    if "ood_type" in heatmaps.columns:
        selected = heatmaps[heatmaps["ood_type"].astype(str) == ood_type].head(3)
    else:
        selected = pd.DataFrame()
    if selected.empty:
        selected = heatmaps.head(3)
    for axis, (_, row) in zip(np.ravel(axes), selected.iterrows()):
        overlay = heatmap_manifest.parent / str(row.get("overlay_file", ""))
        if overlay.exists():
            axis.imshow(Image.open(overlay).convert("RGB"))
        else:
            axis.text(0.5, 0.5, "Missing overlay", ha="center", va="center")
        axis.set_title(_short_subtype(str(row.get("ood_subtype", ood_type))))
        axis.axis("off")
    title = "Sensory artifact heatmap examples" if ood_type == "sensory_artifact" else "Modality shift heatmap examples"
    fig.suptitle(title)
    return _save(fig, path, dpi=dpi)


def _find_heatmap_manifest(reports_dir: Path, experiment: str) -> Path | None:
    eval_dir = reports_dir / "runs" / experiment / "evaluation"
    for dirname in ["selected_heatmaps", "heatmaps"]:
        candidate = eval_dir / dirname / "heatmap_manifest.csv"
        if candidate.exists():
            return candidate
    return None


def _plot_system_pipeline(path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(8.6, 3.0))
    ax.axis("off")
    boxes = [
        (0.05, 0.45, 0.16, 0.22, "Input image"),
        (0.30, 0.45, 0.20, 0.22, "OOD gatekeeper"),
        (0.60, 0.63, 0.18, 0.20, "ACCEPT\nvalid FAF"),
        (0.60, 0.28, 0.18, 0.20, "REJECT\ninvalid/OOD"),
        (0.83, 0.63, 0.14, 0.20, "Downstream\nmodel"),
    ]
    for box in boxes:
        _box(ax, *box)
    _arrow(ax, (0.21, 0.56), (0.30, 0.56))
    _arrow(ax, (0.50, 0.56), (0.60, 0.73))
    _arrow(ax, (0.50, 0.56), (0.60, 0.38))
    _arrow(ax, (0.78, 0.73), (0.83, 0.73))
    ax.set_title("System pipeline overview", pad=14)
    return _save(fig, path, dpi=dpi)


def _plot_dataset_taxonomy(path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(9.2, 5.4))
    ax.axis("off")
    _box(ax, 0.39, 0.86, 0.22, 0.09, "Dataset taxonomy")
    groups = [
        ("id", 0.06, 0.64, _PALETTE["light_green"]),
        ("modality_shift", 0.29, 0.64, _PALETTE["light_blue"]),
        ("sensory_artifact", 0.52, 0.64, _PALETTE["light_gold"]),
        ("semantic_outlier", 0.75, 0.64, _PALETTE["light_red"]),
    ]
    for label, x, y, face in groups:
        _box(ax, x, y, 0.18, 0.09, label, facecolor=face)
        _arrow(ax, (0.50, 0.86), (x + 0.09, y + 0.09))
    subtype_text = {
        "modality_shift": ["colour_fundus", "oct_screenshot"],
        "sensory_artifact": [
            "text_watermark",
            "rectangle_annotation",
            "arrow_annotation",
            "composite_layout",
            "blur_artifact",
            "border_crop",
            "gaussian_noise",
            "jpeg_compression",
        ],
        "semantic_outlier": ["cifar10_natural"],
    }
    for label, x, _, _ in groups[1:]:
        text = "\n".join(subtype_text[label])
        ax.text(x + 0.09, 0.49, text, ha="center", va="top", fontsize=8, linespacing=1.35)
    ax.text(0.15, 0.47, "valid synthetic FAF\ntraining/evaluation ID", ha="center", va="top", fontsize=8)
    ax.set_title("Dataset taxonomy diagram", pad=12)
    return _save(fig, path, dpi=dpi)


def _plot_patchcore_method(path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(8.8, 3.2))
    ax.axis("off")
    boxes = [
        (0.04, 0.45, 0.14, 0.22, "FAF image"),
        (0.25, 0.45, 0.16, 0.22, "ResNet\nfeatures"),
        (0.48, 0.45, 0.16, 0.22, "Selected\nlayers"),
        (0.70, 0.45, 0.16, 0.22, "Memory bank\nID patches"),
        (0.70, 0.12, 0.16, 0.18, "Nearest-neighbor\nscore"),
        (0.48, 0.12, 0.16, 0.18, "Threshold\naccept/reject"),
    ]
    for box in boxes:
        _box(ax, *box)
    _arrow(ax, (0.18, 0.56), (0.25, 0.56))
    _arrow(ax, (0.41, 0.56), (0.48, 0.56))
    _arrow(ax, (0.64, 0.56), (0.70, 0.56))
    _arrow(ax, (0.78, 0.45), (0.78, 0.30))
    _arrow(ax, (0.70, 0.21), (0.64, 0.21))
    ax.text(0.78, 0.82, "trained on ID images only", ha="center", fontsize=8, color=_PALETTE["gray"])
    ax.set_title("PatchCore method", pad=14)
    return _save(fig, path, dpi=dpi)


def _plot_experiment_workflow(path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(8.8, 3.2))
    ax.axis("off")
    boxes = [
        (0.04, 0.46, 0.15, 0.20, "Dataset\npackage"),
        (0.25, 0.46, 0.15, 0.20, "Train on\nID only"),
        (0.47, 0.62, 0.17, 0.18, "Balanced by\nsubtype"),
        (0.47, 0.36, 0.17, 0.18, "Balanced by\ntype / full"),
        (0.70, 0.46, 0.15, 0.20, "Aggregate\nmetrics"),
        (0.88, 0.46, 0.10, 0.20, "Figures"),
    ]
    for box in boxes:
        _box(ax, *box)
    _arrow(ax, (0.19, 0.56), (0.25, 0.56))
    _arrow(ax, (0.40, 0.56), (0.47, 0.71))
    _arrow(ax, (0.40, 0.56), (0.47, 0.45))
    _arrow(ax, (0.64, 0.71), (0.70, 0.56))
    _arrow(ax, (0.64, 0.45), (0.70, 0.56))
    _arrow(ax, (0.85, 0.56), (0.88, 0.56))
    ax.set_title("Experiment workflow diagram", pad=14)
    return _save(fig, path, dpi=dpi)


def _write_caption_suggestions(path: Path, files: dict[str, Path], summary: pd.DataFrame) -> Path:
    warning = _warning_text(summary)
    captions = _figure_metadata(files, warning=warning)
    lines = ["# Caption Suggestions", ""]
    for item in captions:
        lines.extend(
            [
                f"## {item['file'].name}",
                "",
                item["caption"],
                "",
                f"Usage note: {item['section']}.",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_figure_index(path: Path, files: dict[str, Path]) -> Path:
    metadata = _figure_metadata(files, warning="")
    rows = [
        "# Figure Index",
        "",
        "| File | Figure title | Purpose | Recommended dissertation section | Short caption suggestion |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in metadata:
        rows.append(
            "| "
            + " | ".join(
                [
                    item["file"].as_posix(),
                    item["title"],
                    item["purpose"],
                    item["section"],
                    item["caption"],
                ]
            ).replace("\n", " ")
            + " |"
        )
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return path


def _figure_metadata(files: dict[str, Path], *, warning: str) -> list[dict[str, Any]]:
    specs = {
        "roc_overall": (
            "overall ROC comparison",
            "Compare discrimination across unsupervised gatekeeper models.",
            "Results",
            "Overall ROC comparison of the evaluated unsupervised gatekeeper models.",
        ),
        "pr_overall": (
            "overall PR comparison",
            "Compare precision-recall behavior under class imbalance.",
            "Results",
            "Overall precision-recall comparison on the primary OOD benchmark.",
        ),
        "layer_ablation": (
            "PatchCore layer ablation",
            "Show which feature layer choice is strongest.",
            "Results",
            "PatchCore feature-layer ablation across the evaluated ResNet layers.",
        ),
        "per_ood_type": (
            "per-OOD-type comparison",
            "Identify which broad OOD category is easiest or hardest.",
            "Results",
            "Per-OOD-type AUROC comparison for modality, artifact, and semantic outliers.",
        ),
        "per_ood_subtype": (
            "per-OOD-subtype comparison",
            "Show detailed subtype-level strengths and weaknesses.",
            "Results",
            "Subtype-level performance for the selected PatchCore gatekeeper.",
        ),
        "score_distribution": (
            "score distribution with threshold",
            "Explain score separation and deployment thresholding.",
            "Results / Methods",
            "Anomaly score distributions for ID and OOD groups with the selected threshold.",
        ),
        "heatmaps_sensory": (
            "sensory artifact heatmap examples",
            "Show representative artifact localization behavior.",
            "Results / Discussion",
            "Representative sensory artifact heatmap examples from the selected PatchCore model.",
        ),
        "heatmaps_modality": (
            "modality shift heatmap examples",
            "Show wrong-modality responses from the gatekeeper.",
            "Results / Discussion",
            "Representative modality shift heatmap examples from the selected PatchCore model.",
        ),
        "dataset_taxonomy": (
            "dataset taxonomy diagram",
            "Define the ID/OOD taxonomy without implying multiclass training.",
            "Dataset",
            "Dataset taxonomy used for ID-only training and OOD-only evaluation.",
        ),
        "system_pipeline": (
            "system pipeline overview",
            "Explain the binary gatekeeper system role.",
            "Introduction / Methods",
            "System overview: input image, OOD gatekeeper, accept/reject decision.",
        ),
        "patchcore_method": (
            "PatchCore method",
            "Explain the feature-memory-bank method.",
            "Methods",
            "PatchCore method diagram showing feature extraction, memory bank scoring, and thresholding.",
        ),
        "experiment_workflow": (
            "experiment workflow diagram",
            "Summarize train/evaluate/aggregate/figure workflow.",
            "Methods",
            "Experiment workflow from dataset package through evaluation and figure generation.",
        ),
    }
    output: list[dict[str, Any]] = []
    for key, (title, purpose, section, caption) in specs.items():
        if key not in files:
            continue
        if warning and key in {"roc_overall", "pr_overall", "score_distribution"}:
            caption = f"{caption} Note: {warning}."
        output.append(
            {
                "file": files[key],
                "title": title,
                "purpose": purpose,
                "section": section,
                "caption": caption,
            }
        )
    return output


def _labels_scores(table: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    return table["label"].astype(int).to_numpy(), table["score"].astype(float).to_numpy()


def _model_label(row: pd.Series) -> str:
    experiment = str(row.get("experiment", ""))
    model = str(row.get("model", "")).lower()
    layers = str(row.get("layers", "")).strip()
    if "autoencoder" in model or "autoencoder" in experiment.lower():
        return "AE baseline"
    if layers:
        return f"PatchCore {layers.replace('layer', 'L').replace('+', '+')}"
    return experiment


def _model_sort_key(row: pd.Series) -> int:
    if "autoencoder" in str(row.get("experiment", "")).lower():
        return 0
    return 10 + _LAYER_ORDER.get(str(row.get("layers", "")), 99)


def _is_patchcore(summary: pd.DataFrame) -> pd.Series:
    model = summary.get("model", pd.Series("", index=summary.index)).fillna("").astype(str).str.lower()
    experiment = summary["experiment"].astype(str).str.lower()
    return model.str.contains("patchcore") | experiment.str.contains("patchcore")


def _first_threshold(table: pd.DataFrame) -> float | None:
    if "threshold" not in table.columns:
        return None
    values = pd.to_numeric(table["threshold"], errors="coerce").dropna()
    if values.empty:
        return None
    return float(values.iloc[0])


def _draw_heatmap_table(
    ax: plt.Axes,
    pivot: pd.DataFrame,
    *,
    title: str,
    colorbar_label: str,
) -> None:
    values = pivot.to_numpy(dtype=float)
    image = ax.imshow(values, vmin=0.0, vmax=1.0, cmap="Blues")
    ax.set_title(title)
    ax.set_xticks(np.arange(len(pivot.columns)))
    ax.set_xticklabels([str(value) for value in pivot.columns], rotation=25, ha="right")
    ax.set_yticks(np.arange(len(pivot.index)))
    ax.set_yticklabels([str(value) for value in pivot.index])
    for y in range(values.shape[0]):
        for x in range(values.shape[1]):
            if np.isfinite(values[y, x]):
                ax.text(x, y, f"{values[y, x]:.2f}", ha="center", va="center", fontsize=8)
    plt.colorbar(image, ax=ax, label=colorbar_label, fraction=0.046, pad=0.04)


def _empty_axis(ax: plt.Axes, message: str) -> None:
    ax.axis("off")
    ax.text(0.5, 0.5, message, ha="center", va="center")


def _box(
    ax: plt.Axes,
    x: float,
    y: float,
    width: float,
    height: float,
    text: str,
    *,
    facecolor: str = "#F7F8FA",
) -> None:
    patch = FancyBboxPatch(
        (x, y),
        width,
        height,
        boxstyle="round,pad=0.02,rounding_size=0.018",
        linewidth=1.2,
        edgecolor="#3A3F45",
        facecolor=facecolor,
    )
    ax.add_patch(patch)
    ax.text(x + width / 2, y + height / 2, text, ha="center", va="center", fontsize=9)


def _arrow(ax: plt.Axes, start: tuple[float, float], end: tuple[float, float]) -> None:
    ax.add_patch(
        FancyArrowPatch(
            start,
            end,
            arrowstyle="-|>",
            mutation_scale=12,
            linewidth=1.2,
            color="#3A3F45",
        )
    )


def _short_subtype(value: str) -> str:
    value = value.strip()
    if not value or value.lower() == "nan":
        return "example"
    return value.replace("_", " ")


def _warning_text(summary: pd.DataFrame) -> str:
    if "warnings" not in summary.columns:
        return "test ID is synthetic fallback only, not real clinical FAF validation"
    warnings = " ".join(str(value) for value in summary["warnings"].dropna() if str(value).strip())
    if "synthetic fallback" in warnings.lower():
        return "test ID is synthetic fallback only, not real clinical FAF validation"
    return "test ID is synthetic fallback only, not real clinical FAF validation"


def _save(fig: plt.Figure, path: Path, *, dpi: int) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=dpi, facecolor="white")
    plt.close(fig)
    return path
