"""Build dissertation-ready multi-scheme comparison tables and figures."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence

import matplotlib
import numpy as np
import pandas as pd
from sklearn.metrics import roc_curve

matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

from retinal_ood.evaluation.metrics import compute_ood_metrics
from retinal_ood.evaluation.report_tables import dataframe_to_markdown


OOD_TYPE_ORDER = ["modality_shift", "sensory_artifact", "semantic_outlier"]
OOD_SUBTYPE_ORDER = [
    "colour_fundus",
    "oct_screenshot",
    "text_watermark",
    "rectangle_annotation",
    "arrow_annotation",
    "composite_layout",
    "blur_artifact",
    "border_crop",
    "gaussian_noise",
    "jpeg_compression",
    "cifar10_natural",
]
EVAL_SET_ORDER = ["balanced_by_subtype", "balanced_by_type", "full_ood_stress"]
PRIMARY_EVAL_SET = "balanced_by_subtype"


@dataclass(frozen=True)
class RunRoot:
    """A generated grid/report directory for one evaluation set."""

    eval_set: str
    path: Path


@dataclass(frozen=True)
class MultiSchemePackageOutputs:
    """Paths generated by the multi-scheme dissertation package."""

    tables: dict[str, Path]
    figures: dict[str, Path]


@dataclass(frozen=True)
class SchemeSpec:
    scheme: str
    label: str
    method_family: str
    training_data: str
    score_type: str
    expected_strength: str
    expected_weakness: str
    dissertation_role: str
    training_type: str
    feature_space: str
    anomaly_score: str
    localization_support: str
    artifact_sensitivity: str
    modality_sensitivity: str
    compute_cost: str
    interpretability: float
    implementation_complexity: float


SCHEME_SPECS: dict[str, SchemeSpec] = {
    "image_statistics": SchemeSpec(
        "image_statistics",
        "Image statistics",
        "low-level image statistics",
        "train_id only",
        "distance in handcrafted feature space",
        "Catches simple intensity, border, and semantic shifts",
        "Weak for local artifacts and feature-level distribution shifts",
        "negative_control / sanity_baseline",
        "ID only",
        "handcrafted scalar statistics",
        "z-score distance",
        "none",
        "medium",
        "medium",
        "very low",
        0.75,
        0.20,
    ),
    "autoencoder": SchemeSpec(
        "autoencoder",
        "Autoencoder",
        "pixel reconstruction",
        "train_id only",
        "reconstruction error",
        "Simple reconstruction baseline aligned with literature",
        "Can reconstruct or smooth over local OOD artifacts",
        "reconstruction_baseline",
        "ID only",
        "pixel space",
        "reconstruction error",
        "weak",
        "low",
        "medium",
        "low",
        0.55,
        0.40,
    ),
    "global_feature_knn": SchemeSpec(
        "global_feature_knn",
        "Global feature kNN",
        "global feature distance",
        "train_id only",
        "nearest-neighbor distance",
        "Compact feature-space baseline",
        "Global pooling can hide small localized corruptions",
        "feature_baseline",
        "ID only",
        "global CNN embedding",
        "kNN distance",
        "none",
        "medium",
        "high",
        "medium",
        0.55,
        0.45,
    ),
    "mahalanobis_feature": SchemeSpec(
        "mahalanobis_feature",
        "Mahalanobis feature",
        "statistical feature distance",
        "train_id only",
        "Mahalanobis distance",
        "Tests Gaussian feature-distance assumption",
        "Covariance estimate can be brittle with limited ID data",
        "statistical_feature_baseline",
        "ID only",
        "global CNN embedding",
        "Mahalanobis distance",
        "none",
        "medium",
        "high",
        "medium",
        0.60,
        0.50,
    ),
    "patchcore_l1": SchemeSpec(
        "patchcore_l1",
        "PatchCore L1",
        "patch-level feature memory bank",
        "train_id only",
        "patch nearest-neighbor distance",
        "Low-level texture sensitivity",
        "Runtime and memory heavy because of dense shallow patch grids",
        "main_method / layer_ablation",
        "ID only",
        "local CNN patches",
        "patch kNN max score",
        "yes",
        "high",
        "medium",
        "very high",
        0.80,
        0.75,
    ),
    "patchcore_l2": SchemeSpec(
        "patchcore_l2",
        "PatchCore L2",
        "patch-level feature memory bank",
        "train_id only",
        "patch nearest-neighbor distance",
        "Mid-low feature sensitivity",
        "Can overreact to benign local texture variation",
        "main_method / layer_ablation",
        "ID only",
        "local CNN patches",
        "patch kNN max score",
        "yes",
        "high",
        "medium",
        "high",
        0.80,
        0.65,
    ),
    "patchcore_l3": SchemeSpec(
        "patchcore_l3",
        "PatchCore L3",
        "patch-level feature memory bank",
        "train_id only",
        "patch nearest-neighbor distance",
        "Strong mid-level feature-space gatekeeper",
        "Safety threshold still rejects too many ID fallback images",
        "main_method / selected_model",
        "ID only",
        "local CNN patches",
        "patch kNN max score",
        "yes",
        "high",
        "high",
        "high",
        0.85,
        0.65,
    ),
    "patchcore_l4": SchemeSpec(
        "patchcore_l4",
        "PatchCore L4",
        "patch-level feature memory bank",
        "train_id only",
        "patch nearest-neighbor distance",
        "High-level semantic shift sensitivity",
        "Coarse grid can miss local artifacts",
        "main_method / layer_ablation",
        "ID only",
        "local CNN patches",
        "patch kNN max score",
        "yes",
        "medium",
        "high",
        "medium",
        0.80,
        0.60,
    ),
    "patchcore_l2_l3": SchemeSpec(
        "patchcore_l2_l3",
        "PatchCore L2+L3",
        "patch-level feature memory bank",
        "train_id only",
        "patch nearest-neighbor distance",
        "Combines local and mid-level feature cues",
        "Larger memory bank and slower scoring",
        "main_method / layer_ablation",
        "ID only",
        "local CNN patches",
        "patch kNN max score",
        "yes",
        "high",
        "high",
        "very high",
        0.85,
        0.75,
    ),
}

SCHEME_ORDER = list(SCHEME_SPECS)
SCHEME_LABELS = {key: value.label for key, value in SCHEME_SPECS.items()}
PALETTE = {
    "blue": "#2F6F9F",
    "green": "#3B7F5C",
    "red": "#B85C5C",
    "gold": "#B38B2E",
    "gray": "#5B6470",
    "light_blue": "#E7F0F7",
    "light_green": "#E8F3ED",
    "light_red": "#F6E7E7",
    "light_gold": "#F8F1DF",
}


def generate_multi_scheme_comparison_package(
    run_roots: Sequence[RunRoot],
    *,
    results_dir: str | Path = "reports/dissertation_results/multi_scheme_comparison",
    figures_dir: str | Path = "reports/dissertation_figures",
    dpi: int = 300,
) -> MultiSchemePackageOutputs:
    """Generate multi-scheme result tables, figures, and dissertation guide docs."""
    if dpi <= 0:
        raise ValueError("dpi must be positive")
    if not run_roots:
        raise ValueError("At least one run root is required")

    results_dir = Path(results_dir)
    figures_dir = Path(figures_dir)
    results_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    records = _load_run_records(run_roots)
    metrics = _build_metrics_table(records)
    per_type = _build_per_type_table(records)
    per_subtype = _build_per_subtype_table(records)
    threshold = _build_threshold_table(metrics)
    overview = _build_scheme_overview(metrics)
    primary = _primary_metrics(metrics)
    model_selection = _build_model_selection_summary(primary)

    tables: dict[str, Path] = {}
    tables.update(_write_table_pair(results_dir, "scheme_overview", overview, "Scheme Overview"))
    tables.update(_write_table_pair(results_dir, "metrics_by_scheme", primary, "Primary Metrics By Scheme"))
    tables.update(
        _write_table_pair(
            results_dir,
            "metrics_by_scheme_and_eval_set",
            metrics,
            "Metrics By Scheme And Evaluation Set",
        )
    )
    tables.update(_write_table_pair(results_dir, "per_ood_type_by_scheme", per_type, "Per OOD Type By Scheme"))
    tables.update(
        _write_table_pair(
            results_dir,
            "per_ood_subtype_by_scheme",
            per_subtype,
            "Per OOD Subtype By Scheme",
        )
    )
    tables.update(
        _write_table_pair(results_dir, "threshold_policy_by_scheme", threshold, "Threshold Policy By Scheme")
    )
    tables.update(
        _write_table_pair(results_dir, "model_selection_summary", model_selection, "Model Selection Summary")
    )

    figures: dict[str, Path] = {}
    figures["figure_scheme_comparison_matrix.png"] = _plot_scheme_comparison_matrix(
        overview, figures_dir / "figure_scheme_comparison_matrix.png", dpi=dpi
    )
    figures["figure_metrics_by_scheme.png"] = _plot_metrics_by_scheme(
        primary, figures_dir / "figure_metrics_by_scheme.png", dpi=dpi
    )
    figures["figure_metrics_by_scheme_and_eval_set.png"] = _plot_metrics_by_eval_set(
        metrics, figures_dir / "figure_metrics_by_scheme_and_eval_set.png", dpi=dpi
    )
    figures["figure_fpr95_by_scheme.png"] = _plot_fpr95_by_scheme(
        primary, figures_dir / "figure_fpr95_by_scheme.png", dpi=dpi
    )
    figures["figure_per_ood_type_by_scheme.png"] = _plot_per_ood_type(
        per_type, figures_dir / "figure_per_ood_type_by_scheme.png", dpi=dpi
    )
    figures["figure_per_ood_subtype_by_scheme.png"] = _plot_per_ood_subtype(
        per_subtype, figures_dir / "figure_per_ood_subtype_by_scheme.png", dpi=dpi
    )
    figures["figure_model_selection_radar_or_table.png"] = _plot_model_selection_table(
        model_selection, figures_dir / "figure_model_selection_radar_or_table.png", dpi=dpi
    )
    figures["figure_workload_summary.png"] = _plot_workload_summary(
        metrics,
        per_type,
        per_subtype,
        figures_dir / "figure_workload_summary.png",
        dpi=dpi,
    )
    figures["figure_methods_family_diagram.png"] = _plot_methods_family_diagram(
        figures_dir / "figure_methods_family_diagram.png", dpi=dpi
    )
    figures["figure_patchcore_layer_ablation.png"] = _plot_patchcore_layer_ablation(
        primary, overview, figures_dir / "figure_patchcore_layer_ablation.png", dpi=dpi
    )
    figures["figure_threshold_policy_comparison.png"] = _plot_threshold_policy(
        threshold, figures_dir / "figure_threshold_policy_comparison.png", dpi=dpi
    )
    figures["figure_failure_modes_by_scheme.png"] = _plot_failure_modes(
        records, figures_dir / "figure_failure_modes_by_scheme.png", dpi=dpi
    )

    tables["workload_summary.md"] = _write_workload_summary(
        results_dir / "workload_summary.md",
        metrics,
        per_type,
        per_subtype,
        figures,
        tables,
    )
    figures["caption_suggestions.md"] = _write_caption_suggestions(
        figures_dir / "caption_suggestions.md", figures, metrics, model_selection
    )
    figures["figure_selection_guide.md"] = _write_figure_selection_guide(
        figures_dir / "figure_selection_guide.md", figures
    )
    figures["figure_index.md"] = _write_figure_index(figures_dir / "figure_index.md", figures_dir)

    return MultiSchemePackageOutputs(tables=tables, figures=figures)


def _load_run_records(run_roots: Sequence[RunRoot]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for root in run_roots:
        run_root = Path(root.path)
        runs_dir = run_root / "runs"
        if not runs_dir.exists():
            raise FileNotFoundError(f"Run root does not contain runs directory: {runs_dir}")
        for eval_dir in sorted(runs_dir.glob("*/evaluation")):
            metrics_path = eval_dir / "metrics.json"
            scores_path = eval_dir / "scores.csv"
            config_path = eval_dir / "resolved_evaluation_config.json"
            if not metrics_path.exists() or not scores_path.exists() or not config_path.exists():
                continue
            metrics = _read_json(metrics_path)
            config = _read_json(config_path)
            run_name = str(config.get("project", {}).get("run_name") or eval_dir.parent.name)
            scheme = _normalize_scheme(run_name, config)
            key = (root.eval_set, scheme)
            if key in seen:
                continue
            seen.add(key)
            scores = pd.read_csv(scores_path)
            scores = _prepare_scores(scores)
            records.append(
                {
                    "eval_set": root.eval_set,
                    "run_name": run_name,
                    "scheme": scheme,
                    "metrics": metrics,
                    "config": config,
                    "scores": scores,
                    "eval_dir": eval_dir,
                }
            )
    if not records:
        raise FileNotFoundError("No evaluation records found under the supplied run roots")
    return records


def _prepare_scores(scores: pd.DataFrame) -> pd.DataFrame:
    table = scores.copy()
    for column in ["label", "score", "threshold", "prediction"]:
        if column in table.columns:
            table[column] = pd.to_numeric(table[column], errors="coerce")
    if "ood_type" not in table.columns:
        table["ood_type"] = np.where(table["label"].astype(int) == 0, "id", "unknown")
    if "ood_subtype" not in table.columns:
        table["ood_subtype"] = np.where(table["label"].astype(int) == 0, "id", "unknown")
    if "prediction" not in table.columns:
        threshold = _first_numeric(table.get("threshold"))
        table["prediction"] = (table["score"].astype(float) >= threshold).astype(int) if threshold else 0
    return table


def _build_metrics_table(records: Sequence[dict[str, Any]]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for record in records:
        metrics = record["metrics"]
        scores = record["scores"]
        labels = scores["label"].astype(int).to_numpy()
        values = scores["score"].astype(float).to_numpy()
        counts = metrics.get("counts", {})
        confusion = metrics.get("confusion_matrix", {})
        threshold_value = float(metrics.get("threshold", {}).get("value", _first_numeric(scores.get("threshold"))))
        id_count = int(counts.get("id", int((labels == 0).sum())))
        ood_count = int(counts.get("ood", int((labels == 1).sum())))
        fp = int(confusion.get("fp", int(((labels == 0) & (values >= threshold_value)).sum())))
        tp = int(confusion.get("tp", int(((labels == 1) & (values >= threshold_value)).sum())))
        rows.append(
            {
                "eval_set": record["eval_set"],
                "scheme": record["scheme"],
                "scheme_label": SCHEME_LABELS.get(record["scheme"], record["scheme"]),
                "run_name": record["run_name"],
                "method_family": SCHEME_SPECS.get(record["scheme"], _fallback_spec(record["scheme"])).method_family,
                "model": record["config"].get("model", {}).get("name", ""),
                "backbone": record["config"].get("model", {}).get("backbone", ""),
                "layers": _stringify_layers(record["config"].get("model", {}).get("layers", "")),
                "auroc": metrics.get("global", {}).get("auroc", np.nan),
                "auprc": metrics.get("global", {}).get("auprc", np.nan),
                "fpr_at_95_tpr": metrics.get("global", {}).get("fpr_at_95_tpr", np.nan),
                "threshold_at_95_tpr": _threshold_at_95_tpr(labels, values),
                "threshold": threshold_value,
                "threshold_source": metrics.get("threshold", {}).get("source", ""),
                "id_false_rejection_count": fp,
                "id_false_rejection_rate": fp / id_count if id_count else np.nan,
                "ood_recall_at_threshold": tp / ood_count if ood_count else np.nan,
                "id_count": id_count,
                "ood_count": ood_count,
                "total_count": int(counts.get("total", id_count + ood_count)),
                "notes": _row_notes(record),
            }
        )
    table = pd.DataFrame(rows)
    for column in ["auroc", "auprc", "fpr_at_95_tpr", "threshold_at_95_tpr"]:
        table[column] = pd.to_numeric(table[column], errors="coerce")
    return _sort_metrics(table)


def _build_per_type_table(records: Sequence[dict[str, Any]]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for record in records:
        shared = _shared_row(record)
        for ood_type, values in sorted(record["metrics"].get("per_ood_type", {}).items()):
            rows.append(
                {
                    **shared,
                    "ood_type": ood_type,
                    "auroc": values.get("auroc", np.nan),
                    "auprc": values.get("auprc", np.nan),
                    "fpr_at_95_tpr": values.get("fpr_at_95_tpr", np.nan),
                    "id_count": values.get("id_count", np.nan),
                    "ood_count": values.get("ood_count", np.nan),
                }
            )
    return _sort_category(pd.DataFrame(rows), category="ood_type", category_order=OOD_TYPE_ORDER)


def _build_per_subtype_table(records: Sequence[dict[str, Any]]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for record in records:
        scores = record["scores"]
        id_scores = scores[scores["label"].astype(int) == 0]
        shared = _shared_row(record)
        ood_scores = scores[scores["label"].astype(int) == 1].copy()
        for subtype in sorted(str(value) for value in ood_scores["ood_subtype"].dropna().unique() if value):
            subtype_scores = ood_scores[ood_scores["ood_subtype"].astype(str) == subtype]
            subset = pd.concat([id_scores, subtype_scores], ignore_index=True)
            metric_values = _safe_metrics(subset["label"].to_numpy(), subset["score"].to_numpy())
            rows.append(
                {
                    **shared,
                    "ood_type": _first_non_empty(subtype_scores["ood_type"].tolist()),
                    "ood_subtype": subtype,
                    **metric_values,
                    "id_count": int(len(id_scores)),
                    "ood_count": int(len(subtype_scores)),
                }
            )
    return _sort_category(pd.DataFrame(rows), category="ood_subtype", category_order=OOD_SUBTYPE_ORDER)


def _build_threshold_table(metrics: pd.DataFrame) -> pd.DataFrame:
    columns = [
        "eval_set",
        "scheme",
        "scheme_label",
        "threshold",
        "threshold_source",
        "threshold_at_95_tpr",
        "id_false_rejection_count",
        "id_false_rejection_rate",
        "ood_recall_at_threshold",
        "id_count",
        "ood_count",
        "notes",
    ]
    return metrics.loc[:, columns].copy()


def _build_scheme_overview(metrics: pd.DataFrame) -> pd.DataFrame:
    completed = set(metrics["scheme"].astype(str))
    rows: list[dict[str, Any]] = []
    for scheme in SCHEME_ORDER:
        spec = SCHEME_SPECS[scheme]
        status = "completed" if scheme in completed else "not_completed_runtime_limited"
        if scheme == "patchcore_l1" and scheme not in completed:
            reason = "Full L1 run was not completed because the shallow layer creates a dense patch grid."
        elif scheme not in completed:
            reason = "No completed evaluation artifact was available."
        else:
            reason = ""
        rows.append(
            {
                "scheme": spec.scheme,
                "scheme_label": spec.label,
                "method family": spec.method_family,
                "training data": spec.training_data,
                "score type": spec.score_type,
                "expected strength": spec.expected_strength,
                "expected weakness": spec.expected_weakness,
                "dissertation role": spec.dissertation_role,
                "completion_status": status,
                "completion_note": reason,
            }
        )
    return pd.DataFrame(rows)


def _primary_metrics(metrics: pd.DataFrame) -> pd.DataFrame:
    primary = metrics[metrics["eval_set"].astype(str) == PRIMARY_EVAL_SET].copy()
    if primary.empty:
        first_eval = sorted(metrics["eval_set"].astype(str).unique())[0]
        primary = metrics[metrics["eval_set"].astype(str) == first_eval].copy()
    return primary.reset_index(drop=True)


def _build_model_selection_summary(primary: pd.DataFrame) -> pd.DataFrame:
    if primary.empty:
        return pd.DataFrame()
    table = primary.copy()
    table["auroc_rank"] = table["auroc"].rank(ascending=False, method="min")
    table["auprc_rank"] = table["auprc"].rank(ascending=False, method="min")
    table["fpr95_rank"] = table["fpr_at_95_tpr"].rank(ascending=True, method="min")
    table["interpretability_score"] = table["scheme"].map(
        lambda scheme: SCHEME_SPECS.get(str(scheme), _fallback_spec(str(scheme))).interpretability
    )
    table["complexity_score"] = table["scheme"].map(
        lambda scheme: SCHEME_SPECS.get(str(scheme), _fallback_spec(str(scheme))).implementation_complexity
    )
    table["balanced_selection_score"] = (
        table["auroc"].fillna(0)
        + table["auprc"].fillna(0)
        + (1.0 - table["fpr_at_95_tpr"].fillna(1.0))
        + table["interpretability_score"].fillna(0)
        + (1.0 - table["complexity_score"].fillna(1.0))
    ) / 5.0
    table["recommendation"] = np.where(
        table["balanced_selection_score"] == table["balanced_selection_score"].max(),
        "selected_for_discussion",
        "comparison_baseline",
    )
    columns = [
        "eval_set",
        "scheme",
        "scheme_label",
        "method_family",
        "auroc",
        "auprc",
        "fpr_at_95_tpr",
        "id_false_rejection_rate",
        "ood_recall_at_threshold",
        "auroc_rank",
        "auprc_rank",
        "fpr95_rank",
        "interpretability_score",
        "complexity_score",
        "balanced_selection_score",
        "recommendation",
        "notes",
    ]
    return _sort_metrics(table.loc[:, columns])


def _write_table_pair(results_dir: Path, stem: str, table: pd.DataFrame, title: str) -> dict[str, Path]:
    csv_path = results_dir / f"{stem}.csv"
    md_path = results_dir / f"{stem}.md"
    table.to_csv(csv_path, index=False)
    note = (
        "Generated from compact evaluation metrics and score CSVs. Training remained ID-only; "
        "OOD labels were used only for evaluation grouping."
    )
    md_path.write_text(f"# {title}\n\n{note}\n\n{dataframe_to_markdown(table)}\n", encoding="utf-8")
    return {csv_path.name: csv_path, md_path.name: md_path}


def _write_workload_summary(
    path: Path,
    metrics: pd.DataFrame,
    per_type: pd.DataFrame,
    per_subtype: pd.DataFrame,
    figures: dict[str, Path],
    tables: dict[str, Path],
) -> Path:
    completed_schemes = metrics["scheme"].nunique()
    patchcore_variants = metrics[metrics["scheme"].astype(str).str.startswith("patchcore_")]["scheme"].nunique()
    eval_sets = metrics["eval_set"].nunique()
    ood_types = per_type["ood_type"].nunique() if not per_type.empty else 0
    ood_subtypes = per_subtype["ood_subtype"].nunique() if not per_subtype.empty else 0
    total_images = int(metrics["total_count"].sum())
    lines = [
        "# Workload Summary",
        "",
        "- number of schemes implemented: " + str(completed_schemes),
        "- number of PatchCore layer variants completed: " + str(patchcore_variants),
        "- number of evaluation subsets: " + str(eval_sets),
        "- number of OOD types: " + str(ood_types),
        "- number of OOD subtypes: " + str(ood_subtypes),
        "- number of figures generated: " + str(len([p for p in figures if p.endswith(".png")])),
        "- number of tables generated: " + str(len([p for p in tables if p.endswith(".csv") or p.endswith(".md")]) + 1),
        "- total dataset images evaluated across completed scheme/evaluation runs: " + str(total_images),
        "- training remained ID-only: yes, only `label=0` / `ood_type=id` train manifests were used.",
        "- OOD was evaluation-only: yes, OOD categories were used for metrics grouping and stress testing only.",
        "- model decision: binary ACCEPT valid FAF / REJECT invalid or OOD input.",
        "- synthetic fallback warning: `test_id_synthetic_fallback.csv` is not real clinical FAF validation.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _plot_scheme_comparison_matrix(overview: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    rows = []
    completed = overview.set_index("scheme")["completion_status"].to_dict()
    for scheme in SCHEME_ORDER:
        spec = SCHEME_SPECS[scheme]
        rows.append(
            {
                "scheme_label": spec.label,
                "Training": "ID-only",
                "Feature space": _matrix_feature_space(spec.feature_space),
                "Score": _matrix_score(spec.anomaly_score),
                "Localization": spec.localization_support,
                "Artifact sens.": spec.artifact_sensitivity,
                "Modality sens.": spec.modality_sensitivity,
                "Compute": spec.compute_cost,
                "Status": str(completed.get(scheme, "not_completed")).replace("not_completed_runtime_limited", "runtime-limited"),
            }
        )
    table = pd.DataFrame(rows)
    display_columns = [
        "Training",
        "Feature space",
        "Score",
        "Localization",
        "Artifact sens.",
        "Modality sens.",
        "Compute",
        "Status",
    ]
    fig, ax = plt.subplots(figsize=(14.0, 6.2))
    ax.axis("off")
    cell_text = table[display_columns].astype(str).values.tolist()
    mpl_table = ax.table(
        cellText=cell_text,
        rowLabels=table["scheme_label"].tolist(),
        colLabels=display_columns,
        cellLoc="left",
        rowLoc="center",
        loc="center",
    )
    mpl_table.auto_set_font_size(False)
    mpl_table.set_fontsize(7.6)
    mpl_table.scale(1.0, 1.42)
    for key, cell in mpl_table.get_celld().items():
        cell.set_edgecolor("#D1D5DB")
        if key[0] == 0:
            cell.set_facecolor("#F3F4F6")
            cell.set_text_props(weight="bold")
    ax.set_title("Scheme comparison matrix", pad=18)
    return _save(fig, path, dpi=dpi)


def _plot_metrics_by_scheme(primary: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(max(8.2, len(primary) * 1.05), 5.0))
    if primary.empty:
        return _empty_plot(fig, ax, path, "No primary metrics available", dpi=dpi)
    x = np.arange(len(primary))
    width = 0.25
    ax.bar(x - width, primary["auroc"], width, label="AUROC", color=PALETTE["blue"])
    ax.bar(x, primary["auprc"], width, label="AUPRC", color=PALETTE["green"])
    ax.bar(x + width, primary["fpr_at_95_tpr"], width, label="FPR@95%TPR", color=PALETTE["red"])
    ax.set_xticks(x)
    ax.set_xticklabels(primary["scheme_label"], rotation=28, ha="right")
    ax.set_ylim(0.0, 1.05)
    ax.set_ylabel("Metric value")
    ax.set_title("Primary multi-scheme OOD gatekeeper comparison")
    ax.legend(frameon=False, ncols=3)
    ax.grid(axis="y", alpha=0.22)
    return _save(fig, path, dpi=dpi)


def _plot_metrics_by_eval_set(metrics: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    pivot = metrics.pivot_table(
        index="scheme_label",
        columns="eval_set",
        values="auroc",
        aggfunc="first",
        sort=False,
    )
    pivot = pivot.reindex(columns=[name for name in EVAL_SET_ORDER if name in pivot.columns])
    fig, ax = plt.subplots(figsize=(8.4, max(4.8, len(pivot) * 0.45)))
    _draw_heatmap(ax, pivot, title="AUROC by scheme and evaluation set", colorbar_label="AUROC")
    return _save(fig, path, dpi=dpi)


def _plot_fpr95_by_scheme(primary: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(max(8.2, len(primary) * 1.0), 4.8))
    if primary.empty:
        return _empty_plot(fig, ax, path, "No primary FPR@95%TPR rows available", dpi=dpi)
    colors = [PALETTE["red"] if value > 0.5 else PALETTE["blue"] for value in primary["fpr_at_95_tpr"]]
    ax.bar(primary["scheme_label"], primary["fpr_at_95_tpr"], color=colors)
    ax.axhline(0.5, color=PALETTE["gray"], linestyle="--", linewidth=1.0)
    ax.set_ylim(0.0, 1.0)
    ax.set_ylabel("FPR@95%TPR (lower is better)")
    ax.set_title("Clinical safety view: false positive rate at 95% OOD recall")
    ax.tick_params(axis="x", rotation=28)
    ax.grid(axis="y", alpha=0.22)
    return _save(fig, path, dpi=dpi)


def _plot_per_ood_type(per_type: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(8.6, 5.2))
    primary = per_type[per_type["eval_set"].astype(str) == PRIMARY_EVAL_SET].copy()
    if primary.empty:
        return _empty_plot(fig, ax, path, "No per-OOD-type rows available", dpi=dpi)
    primary["ood_type"] = pd.Categorical(primary["ood_type"], OOD_TYPE_ORDER, ordered=True)
    pivot = primary.pivot_table(
        index="scheme_label",
        columns="ood_type",
        values="auroc",
        aggfunc="first",
        sort=False,
        observed=False,
    )
    _draw_heatmap(ax, pivot, title="Primary AUROC by OOD type and scheme", colorbar_label="AUROC")
    return _save(fig, path, dpi=dpi)


def _plot_per_ood_subtype(per_subtype: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(11.2, 5.8))
    primary = per_subtype[per_subtype["eval_set"].astype(str) == PRIMARY_EVAL_SET].copy()
    if primary.empty:
        return _empty_plot(fig, ax, path, "No per-OOD-subtype rows available", dpi=dpi)
    selected = [
        "image_statistics",
        "autoencoder",
        "global_feature_knn",
        "mahalanobis_feature",
        "patchcore_l3",
        "patchcore_l2_l3",
    ]
    primary = primary[primary["scheme"].isin(selected)]
    primary["ood_subtype"] = pd.Categorical(primary["ood_subtype"], OOD_SUBTYPE_ORDER, ordered=True)
    pivot = primary.pivot_table(
        index="scheme_label",
        columns="ood_subtype",
        values="auroc",
        aggfunc="first",
        sort=False,
        observed=False,
    )
    _draw_heatmap(ax, pivot, title="Primary AUROC by OOD subtype", colorbar_label="AUROC", annotate=False)
    ax.tick_params(axis="x", labelsize=8)
    return _save(fig, path, dpi=dpi)


def _plot_model_selection_table(model_selection: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(10.8, 5.2))
    ax.axis("off")
    if model_selection.empty:
        return _empty_plot(fig, ax, path, "No model-selection rows available", dpi=dpi)
    display = model_selection[
        [
            "scheme_label",
            "auroc",
            "auprc",
            "fpr_at_95_tpr",
            "interpretability_score",
            "complexity_score",
            "balanced_selection_score",
        ]
    ].copy()
    for column in display.columns[1:]:
        display[column] = display[column].map(lambda value: f"{float(value):.3f}")
    mpl_table = ax.table(
        cellText=display.values.tolist(),
        colLabels=[
            "Scheme",
            "AUROC",
            "AUPRC",
            "FPR@95",
            "Interp.",
            "Complexity",
            "Balanced",
        ],
        cellLoc="center",
        loc="center",
    )
    mpl_table.auto_set_font_size(False)
    mpl_table.set_fontsize(8)
    mpl_table.scale(1.0, 1.45)
    for key, cell in mpl_table.get_celld().items():
        cell.set_edgecolor("#D1D5DB")
        if key[0] == 0:
            cell.set_facecolor("#F3F4F6")
            cell.set_text_props(weight="bold")
    ax.set_title("Model selection trade-off table", pad=16)
    return _save(fig, path, dpi=dpi)


def _plot_workload_summary(
    metrics: pd.DataFrame,
    per_type: pd.DataFrame,
    per_subtype: pd.DataFrame,
    path: Path,
    *,
    dpi: int,
) -> Path:
    cards = [
        ("Schemes", metrics["scheme"].nunique()),
        ("PatchCore variants", metrics[metrics["scheme"].astype(str).str.startswith("patchcore_")]["scheme"].nunique()),
        ("Evaluation sets", metrics["eval_set"].nunique()),
        ("OOD types", per_type["ood_type"].nunique() if not per_type.empty else 0),
        ("OOD subtypes", per_subtype["ood_subtype"].nunique() if not per_subtype.empty else 0),
        ("Images x runs", int(metrics["total_count"].sum())),
    ]
    fig, ax = plt.subplots(figsize=(9.4, 4.8))
    ax.axis("off")
    positions = [(0.06, 0.56), (0.37, 0.56), (0.68, 0.56), (0.06, 0.20), (0.37, 0.20), (0.68, 0.20)]
    faces = [
        PALETTE["light_blue"],
        PALETTE["light_green"],
        PALETTE["light_gold"],
        PALETTE["light_red"],
        "#F3F4F6",
        PALETTE["light_blue"],
    ]
    for (label, value), (x, y), face in zip(cards, positions, faces):
        _box(ax, x, y, 0.24, 0.22, "", facecolor=face)
        ax.text(x + 0.12, y + 0.145, f"{value:,}", ha="center", va="center", fontsize=18, weight="bold")
        ax.text(x + 0.12, y + 0.065, label, ha="center", va="center", fontsize=9)
    ax.text(
        0.5,
        0.07,
        "Training remained ID-only; OOD categories were used only for evaluation grouping.",
        ha="center",
        va="center",
        fontsize=9,
        color=PALETTE["gray"],
    )
    ax.set_title("Experiment workload summary", pad=12)
    return _save(fig, path, dpi=dpi)


def _plot_methods_family_diagram(path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(10.0, 4.2))
    ax.axis("off")
    _box(ax, 0.04, 0.56, 0.14, 0.16, "Input FAF\nimage")
    family_boxes = [
        (0.27, 0.78, "Pixel\nreconstruction", "AE"),
        (0.27, 0.55, "Global feature\ndistance", "kNN"),
        (0.27, 0.32, "Statistical feature\ndistance", "Mahalanobis"),
        (0.27, 0.09, "Patch memory\nbank", "PatchCore"),
    ]
    for x, y, title, scheme in family_boxes:
        _box(ax, x, y, 0.20, 0.13, title)
        _box(ax, 0.55, y, 0.16, 0.13, scheme, facecolor=PALETTE["light_blue"])
        _arrow(ax, (0.18, 0.64), (x, y + 0.065))
        _arrow(ax, (x + 0.20, y + 0.065), (0.55, y + 0.065))
        _arrow(ax, (0.71, y + 0.065), (0.82, 0.47))
    _box(ax, 0.82, 0.39, 0.14, 0.16, "Anomaly\nscore")
    _box(ax, 0.82, 0.15, 0.14, 0.14, "ACCEPT /\nREJECT")
    _arrow(ax, (0.89, 0.39), (0.89, 0.29))
    ax.set_title("Method family diagram", pad=12)
    return _save(fig, path, dpi=dpi)


def _plot_patchcore_layer_ablation(primary: pd.DataFrame, overview: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    fig, ax = plt.subplots(figsize=(7.6, 4.8))
    layer_order = ["patchcore_l1", "patchcore_l2", "patchcore_l3", "patchcore_l4", "patchcore_l2_l3"]
    rows = primary.set_index("scheme").reindex(layer_order)
    labels = [SCHEME_LABELS[name] for name in layer_order]
    x = np.arange(len(layer_order))
    ax.plot(x, rows["auroc"], marker="o", label="AUROC", color=PALETTE["blue"])
    ax.plot(x, rows["auprc"], marker="o", label="AUPRC", color=PALETTE["green"])
    ax.plot(x, rows["fpr_at_95_tpr"], marker="o", label="FPR@95%TPR", color=PALETTE["red"])
    missing = [idx for idx, value in enumerate(rows["auroc"]) if pd.isna(value)]
    for idx in missing:
        ax.scatter(idx, 0.04, marker="x", s=70, color=PALETTE["gray"])
        ax.text(idx, 0.09, "not run", ha="center", fontsize=8, color=PALETTE["gray"])
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=24, ha="right")
    ax.set_ylim(0.0, 1.05)
    ax.set_ylabel("Metric value")
    ax.set_title("PatchCore layer ablation")
    ax.legend(frameon=False, ncols=3, fontsize=8)
    ax.grid(axis="y", alpha=0.22)
    return _save(fig, path, dpi=dpi)


def _plot_threshold_policy(threshold: pd.DataFrame, path: Path, *, dpi: int) -> Path:
    primary = threshold[threshold["eval_set"].astype(str) == PRIMARY_EVAL_SET].copy()
    fig, ax = plt.subplots(figsize=(max(8.2, len(primary) * 1.0), 5.0))
    if primary.empty:
        return _empty_plot(fig, ax, path, "No threshold-policy rows available", dpi=dpi)
    x = np.arange(len(primary))
    width = 0.34
    ax.bar(x - width / 2, primary["id_false_rejection_rate"], width, color=PALETTE["red"], label="ID false rejection")
    ax.bar(x + width / 2, primary["ood_recall_at_threshold"], width, color=PALETTE["blue"], label="OOD recall at deployment threshold")
    ax.set_xticks(x)
    ax.set_xticklabels(primary["scheme_label"], rotation=28, ha="right")
    ax.set_ylim(0.0, 1.05)
    ax.set_ylabel("Rate")
    ax.set_title("Deployment threshold trade-off")
    ax.legend(frameon=False)
    ax.grid(axis="y", alpha=0.22)
    return _save(fig, path, dpi=dpi)


def _plot_failure_modes(records: Sequence[dict[str, Any]], path: Path, *, dpi: int) -> Path:
    rows: list[dict[str, Any]] = []
    for record in records:
        if record["eval_set"] != PRIMARY_EVAL_SET:
            continue
        scores = record["scores"]
        ood = scores[scores["label"].astype(int) == 1].copy()
        for ood_type in OOD_TYPE_ORDER:
            subset = ood[ood["ood_type"].astype(str) == ood_type]
            if subset.empty:
                continue
            miss_rate = float((subset["prediction"].astype(int) == 0).mean())
            rows.append(
                {
                    "scheme_label": SCHEME_LABELS.get(record["scheme"], record["scheme"]),
                    "ood_type": ood_type,
                    "miss_rate": miss_rate,
                }
            )
    table = pd.DataFrame(rows)
    fig, ax = plt.subplots(figsize=(8.2, 5.0))
    if table.empty:
        return _empty_plot(fig, ax, path, "No primary prediction rows available", dpi=dpi)
    table["ood_type"] = pd.Categorical(table["ood_type"], OOD_TYPE_ORDER, ordered=True)
    pivot = table.pivot_table(
        index="scheme_label",
        columns="ood_type",
        values="miss_rate",
        aggfunc="first",
        sort=False,
        observed=False,
    )
    _draw_heatmap(ax, pivot, title="OOD miss-rate failure modes by scheme", colorbar_label="Miss rate")
    return _save(fig, path, dpi=dpi)


def _write_caption_suggestions(
    path: Path,
    figures: dict[str, Path],
    metrics: pd.DataFrame,
    model_selection: pd.DataFrame,
) -> Path:
    best = _best_scheme_label(model_selection)
    warning = "`test_id_synthetic_fallback.csv` is synthetic fallback ID, not real clinical FAF validation."
    captions = {
        "figure_roc_overall_model_comparison.png": f"Overall ROC comparison for the original AE/PatchCore model set on the primary evaluation split. {warning}",
        "figure_pr_overall_model_comparison.png": f"Overall precision-recall comparison for the original AE/PatchCore model set on the primary evaluation split. {warning}",
        "figure_layer_ablation_patchcore.png": "Original PatchCore layer-ablation figure from the primary result package.",
        "figure_per_ood_type_comparison.png": "Original per-OOD-type comparison for the AE/PatchCore primary result package.",
        "figure_per_ood_subtype_comparison.png": "Original per-OOD-subtype comparison for the selected PatchCore result package.",
        "figure_score_distribution_with_threshold.png": "Score distribution for the selected PatchCore model with the validation-ID threshold overlaid.",
        "figure_score_distribution_id_vs_ood.png": "ID versus OOD anomaly-score distribution for the selected PatchCore model.",
        "figure_heatmaps_sensory_artifact_examples.png": "Representative sensory artifact heatmap examples for the selected PatchCore model.",
        "figure_heatmaps_modality_examples.png": "Representative modality-shift heatmap examples for the selected PatchCore model.",
        "figure_dataset_taxonomy.png": "Dataset taxonomy diagram showing ID, modality shift, sensory artifact, and semantic outlier categories while preserving binary accept/reject modelling.",
        "figure_system_pipeline_overview.png": "System pipeline overview showing the OOD gatekeeper as an upstream binary accept/reject component.",
        "figure_patchcore_method.png": "PatchCore method diagram showing feature extraction, ID patch memory, nearest-neighbor scoring, and thresholding.",
        "figure_experiment_workflow.png": "Experiment workflow diagram from dataset package through ID-only training, OOD evaluation, aggregation, and figure generation.",
        "figure_threshold_policy.png": "Original threshold-policy visualization for the selected PatchCore model.",
        "figure_scheme_comparison_matrix.png": "Matrix of evaluated unsupervised OOD gatekeeper schemes, showing training type, feature space, anomaly score, localization support, sensitivity expectations, compute cost, and completion status.",
        "figure_workload_summary.png": "Summary of project workload across schemes, PatchCore variants, evaluation sets, OOD categories, subtypes, and evaluated images.",
        "figure_metrics_by_scheme.png": f"Primary balanced-by-subtype comparison of AUROC, AUPRC, and FPR@95%TPR across completed schemes. {warning}",
        "figure_fpr95_by_scheme.png": "Safety-focused view of FPR@95%TPR for the primary evaluation split; lower values indicate fewer ID false rejections at high OOD recall.",
        "figure_per_ood_type_by_scheme.png": "Per-OOD-type AUROC heatmap for modality shifts, sensory artifacts, and semantic outliers.",
        "figure_per_ood_subtype_by_scheme.png": "Subtype-level AUROC heatmap across the 11 OOD subtypes used for stress testing.",
        "figure_patchcore_layer_ablation.png": "PatchCore layer ablation showing the effect of feature layer selection; runtime-limited variants are marked explicitly rather than imputed.",
        "figure_threshold_policy_comparison.png": "Deployment threshold trade-off comparing ID false rejection rate and OOD recall at the validation-ID threshold.",
        "figure_methods_family_diagram.png": "Method-family overview grouping reconstruction, global feature distance, statistical feature distance, and patch-level memory-bank approaches.",
        "figure_model_selection_radar_or_table.png": f"Trade-off summary used to motivate {best} as the selected discussion model while retaining safety caveats.",
        "figure_failure_modes_by_scheme.png": "Observed OOD miss-rate patterns by broad OOD type, derived from completed primary predictions.",
        "figure_metrics_by_scheme_and_eval_set.png": "AUROC stability comparison across the primary, secondary, and stress OOD evaluation sets.",
    }
    lines = ["# Caption Suggestions", ""]
    for name in sorted(captions):
        if name not in figures and not (path.parent / name).exists():
            continue
        lines.extend([f"## {name}", "", captions[name], ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_figure_selection_guide(path: Path, figures: dict[str, Path]) -> Path:
    must_include = [
        "figure_scheme_comparison_matrix.png",
        "figure_workload_summary.png",
        "figure_metrics_by_scheme.png",
        "figure_fpr95_by_scheme.png",
        "figure_per_ood_type_by_scheme.png",
        "figure_per_ood_subtype_by_scheme.png",
        "figure_patchcore_layer_ablation.png",
        "figure_threshold_policy_comparison.png",
        "figure_system_pipeline_overview.png",
        "figure_dataset_taxonomy.png",
        "figure_heatmaps_sensory_artifact_examples.png",
        "figure_heatmaps_modality_examples.png",
    ]
    optional = [
        "figure_metrics_by_scheme_and_eval_set.png",
        "figure_model_selection_radar_or_table.png",
        "figure_methods_family_diagram.png",
        "figure_failure_modes_by_scheme.png",
        "figure_roc_overall_model_comparison.png",
        "figure_pr_overall_model_comparison.png",
    ]
    backup = [
        "figure_metric_bars_main_models.png",
        "figure_score_distribution_with_threshold.png",
        "figure_threshold_policy.png",
    ]
    do_not_use = [
        "Raw generated run plots that include private local paths or unresolved experiment folders.",
    ]
    lines = ["# Figure Selection Guide", ""]
    for heading, names in [
        ("must_include", must_include),
        ("optional", optional),
        ("backup", backup),
        ("do_not_use", do_not_use),
    ]:
        lines.extend([f"## {heading}", ""])
        for name in names:
            marker = "available" if (path.parent / name).exists() or name in figures else "not regenerated"
            if heading == "do_not_use":
                lines.append(f"- {name}")
            else:
                lines.append(f"- `{name}` - {marker}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_figure_index(path: Path, figures_dir: Path) -> Path:
    rows = [
        "# Figure Index",
        "",
        "| File | Recommended use | Notes |",
        "| --- | --- | --- |",
    ]
    for figure in sorted(figures_dir.glob("figure_*.png")):
        role = _figure_role(figure.name)
        rows.append(f"| {figure.name} | {role} | Dissertation-ready PNG, white background. |")
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return path


def _draw_heatmap(
    ax: plt.Axes,
    pivot: pd.DataFrame,
    *,
    title: str,
    colorbar_label: str,
    annotate: bool = True,
) -> None:
    values = pivot.to_numpy(dtype=float)
    image = ax.imshow(values, vmin=0.0, vmax=1.0, cmap="Blues")
    ax.set_title(title)
    ax.set_xticks(np.arange(len(pivot.columns)))
    ax.set_xticklabels([str(value) for value in pivot.columns], rotation=28, ha="right")
    ax.set_yticks(np.arange(len(pivot.index)))
    ax.set_yticklabels([str(value) for value in pivot.index])
    if annotate:
        for y in range(values.shape[0]):
            for x in range(values.shape[1]):
                if np.isfinite(values[y, x]):
                    ax.text(x, y, f"{values[y, x]:.2f}", ha="center", va="center", fontsize=8)
    plt.colorbar(image, ax=ax, label=colorbar_label, fraction=0.046, pad=0.04)


def _box(
    ax: plt.Axes,
    x: float,
    y: float,
    width: float,
    height: float,
    text: str,
    *,
    facecolor: str = "#F7F8FA",
) -> None:
    patch = FancyBboxPatch(
        (x, y),
        width,
        height,
        boxstyle="round,pad=0.02,rounding_size=0.018",
        linewidth=1.2,
        edgecolor="#3A3F45",
        facecolor=facecolor,
    )
    ax.add_patch(patch)
    ax.text(x + width / 2, y + height / 2, text, ha="center", va="center", fontsize=9)


def _arrow(ax: plt.Axes, start: tuple[float, float], end: tuple[float, float]) -> None:
    ax.add_patch(
        FancyArrowPatch(
            start,
            end,
            arrowstyle="-|>",
            mutation_scale=12,
            linewidth=1.2,
            color="#3A3F45",
        )
    )


def _save(fig: plt.Figure, path: Path, *, dpi: int) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=dpi, facecolor="white")
    plt.close(fig)
    return path


def _empty_plot(fig: plt.Figure, ax: plt.Axes, path: Path, message: str, *, dpi: int) -> Path:
    ax.axis("off")
    ax.text(0.5, 0.5, message, ha="center", va="center")
    return _save(fig, path, dpi=dpi)


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON must contain an object: {path}")
    return data


def _normalize_scheme(run_name: str, config: dict[str, Any]) -> str:
    name = run_name.lower()
    model_name = str(config.get("model", {}).get("name", "")).lower()
    layers = _stringify_layers(config.get("model", {}).get("layers", "")).lower()
    if "image_statistics" in name or model_name == "image_statistics":
        return "image_statistics"
    if "autoencoder" in name or "autoencoder" in model_name:
        return "autoencoder"
    if "global_feature_knn" in name or model_name == "global_feature_knn":
        return "global_feature_knn"
    if "mahalanobis" in name or model_name == "mahalanobis_feature":
        return "mahalanobis_feature"
    if "patchcore" in name or model_name == "patchcore":
        if "layer2+layer3" in layers or "layer2_layer3" in name:
            return "patchcore_l2_l3"
        if "layer1" in layers or "layer1" in name:
            return "patchcore_l1"
        if "layer2" in layers or "layer2" in name:
            return "patchcore_l2"
        if "layer3" in layers or "layer3" in name:
            return "patchcore_l3"
        if "layer4" in layers or "layer4" in name:
            return "patchcore_l4"
    return name


def _stringify_layers(layers: Any) -> str:
    if isinstance(layers, (list, tuple)):
        return "+".join(str(layer) for layer in layers)
    if layers is None:
        return ""
    return str(layers)


def _threshold_at_95_tpr(labels: np.ndarray, scores: np.ndarray) -> float:
    labels = labels.astype(int)
    scores = scores.astype(float)
    if labels.size == 0 or len(np.unique(labels)) < 2:
        return float("nan")
    _, tpr, thresholds = roc_curve(labels, scores, pos_label=1, drop_intermediate=False)
    eligible = np.where(tpr >= 0.95)[0]
    if eligible.size == 0:
        return float("nan")
    finite = thresholds[eligible][np.isfinite(thresholds[eligible])]
    if finite.size == 0:
        return float("nan")
    return float(finite[0])


def _safe_metrics(labels: np.ndarray, scores: np.ndarray) -> dict[str, float]:
    try:
        result = compute_ood_metrics(labels.astype(int), scores.astype(float))
    except ValueError:
        return {"auroc": np.nan, "auprc": np.nan, "fpr_at_95_tpr": np.nan}
    return {
        "auroc": result.auroc,
        "auprc": result.auprc,
        "fpr_at_95_tpr": result.fpr_at_95_tpr,
    }


def _first_numeric(values: Any) -> float:
    if values is None:
        return float("nan")
    series = pd.to_numeric(pd.Series(values), errors="coerce").dropna()
    return float(series.iloc[0]) if not series.empty else float("nan")


def _shared_row(record: dict[str, Any]) -> dict[str, Any]:
    scheme = str(record["scheme"])
    return {
        "eval_set": record["eval_set"],
        "scheme": scheme,
        "scheme_label": SCHEME_LABELS.get(scheme, scheme),
        "run_name": record["run_name"],
    }


def _first_non_empty(values: Iterable[Any]) -> str:
    for value in values:
        text = str(value).strip()
        if text and text.lower() != "nan":
            return text
    return ""


def _fallback_spec(scheme: str) -> SchemeSpec:
    return SchemeSpec(
        scheme,
        scheme,
        "unspecified",
        "train_id only",
        "anomaly score",
        "",
        "",
        "comparison",
        "ID only",
        "",
        "",
        "",
        "",
        "",
        "",
        0.5,
        0.5,
    )


def _matrix_feature_space(value: str) -> str:
    replacements = {
        "handcrafted scalar statistics": "image stats",
        "global CNN embedding": "global CNN",
        "local CNN patches": "local patches",
    }
    return replacements.get(value, value)


def _matrix_score(value: str) -> str:
    replacements = {
        "distance in handcrafted feature space": "z-score distance",
        "reconstruction error": "recon error",
        "nearest-neighbor distance": "kNN distance",
        "Mahalanobis distance": "Mahalanobis",
        "patch kNN max score": "patch kNN max",
    }
    return replacements.get(value, value)


def _row_notes(record: dict[str, Any]) -> str:
    config = record["config"]
    test_id_manifest = str(config.get("data", {}).get("test_id_manifest", ""))
    notes = []
    if "test_id_synthetic_fallback" in test_id_manifest:
        notes.append("synthetic ID fallback; not real clinical FAF validation")
    notes.append("training ID-only; OOD evaluation-only")
    return "; ".join(notes)


def _sort_metrics(table: pd.DataFrame) -> pd.DataFrame:
    if table.empty:
        return table
    eval_rank = {name: index for index, name in enumerate(EVAL_SET_ORDER)}
    scheme_rank = {name: index for index, name in enumerate(SCHEME_ORDER)}
    table = table.copy()
    table["_eval_rank"] = table["eval_set"].map(lambda value: eval_rank.get(str(value), 99))
    table["_scheme_rank"] = table["scheme"].map(lambda value: scheme_rank.get(str(value), 99))
    table = table.sort_values(["_eval_rank", "_scheme_rank", "scheme"], kind="stable")
    return table.drop(columns=["_eval_rank", "_scheme_rank"]).reset_index(drop=True)


def _sort_category(table: pd.DataFrame, *, category: str, category_order: Sequence[str]) -> pd.DataFrame:
    if table.empty:
        return table
    eval_rank = {name: index for index, name in enumerate(EVAL_SET_ORDER)}
    scheme_rank = {name: index for index, name in enumerate(SCHEME_ORDER)}
    cat_rank = {name: index for index, name in enumerate(category_order)}
    table = table.copy()
    table["_eval_rank"] = table["eval_set"].map(lambda value: eval_rank.get(str(value), 99))
    table["_scheme_rank"] = table["scheme"].map(lambda value: scheme_rank.get(str(value), 99))
    table["_cat_rank"] = table[category].map(lambda value: cat_rank.get(str(value), 99))
    table = table.sort_values(["_eval_rank", "_scheme_rank", "_cat_rank", category], kind="stable")
    return table.drop(columns=["_eval_rank", "_scheme_rank", "_cat_rank"]).reset_index(drop=True)


def _best_scheme_label(model_selection: pd.DataFrame) -> str:
    if model_selection.empty:
        return "the selected gatekeeper"
    row = model_selection.sort_values("balanced_selection_score", ascending=False).iloc[0]
    return str(row["scheme_label"])


def _figure_role(name: str) -> str:
    if "scheme_comparison_matrix" in name or "workload" in name:
        return "must_include"
    if "metrics_by_scheme" in name or "fpr95" in name:
        return "must_include"
    if "per_ood" in name or "patchcore_layer_ablation" in name:
        return "must_include"
    if "threshold_policy_comparison" in name:
        return "must_include"
    if "pipeline" in name or "taxonomy" in name or "heatmaps" in name:
        return "must_include"
    return "optional"
